version: '3'

services:
  postgres:
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  khairat-api:
    build:
      context: ./api/khairat-api
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  tabung-api:
    build:
      context: ./api/tabung-api
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  cadangan-api:
    build:
      context: ./api/cadangan-api
    ports:
      - "8083:8083"
    depends_on:
      - postgres

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - khairat-api
      - tabung-api
      - cadangan-api

  public-web:
    build:
      context: ./public-web
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    depends_on:
      - khairat-api
      - tabung-api
      - cadangan-api

